### PR TITLE
Add guide categories

### PR DESCRIPTION
**Pull request by hoshsadiq**
Hello, this moves the categories to the top of the pvr guide similar to how estuary does it. I wasn't able to keep the categories where it used to be (that is - in the options menu) as for some reason it refused to keep the categories there (it showed just the icon). This is something that I wanted to see myself, but also it's been [requested on the Kodi forums](https://forum.kodi.tv/showthread.php?tid=344664)

image

image

Please note, I'm not a designer, so I wasn't quite sure what to do with the active category (as you can see I based on the "currently selected one" on the same thing as the main guide rows),  that is currently active category while in the main guide window (as in screenshot 2). If you have suggestions, please do let me know.

### CODE REVIEW

**Comment by sandeep-ma** [comment]
Does this show up only in guide view? What about channels view? We need to be easily switch groups in channel view also. I dont use guide view since there is nothing there.

**Comment by hoshsadiq** [comment]
This is only the guide view. Reason I didn't add it channel view is because it doesn't conflict with the current buttons. Left and right have no use, and so simply pressing left and right isn't an issue to get to category filters.

Anyway, I've just noticed that this would overlap with the now playing layout so I will look at fixing this soon.

**Comment by hoshsadiq** [comment]
@xhaggi would you be willing to approve this providing I fix the above issue? If so, do you have any suggestions?

**Comment by hoshsadiq** [comment]
Thinking something like this:

Screenshot from 2019-09-18 20-51-20

Though I'm not sure how to implement it. Tried using a conditional include, setting the width as a variable and tried using animating, but to no avail. Any ideas?

**Pull request closed without merging**
